### ISSUE TITLE
New ballot does not open modal dialog

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/openslides-voting#64]
When you click 
![image](https://user-images.githubusercontent.com/20415092/42155811-b0009e78-7de9-11e8-92da-c853013c5a18.png) and select "VoteCollector" as Type you get a JavaScript error and the modal dialog does not open.

![image](https://user-images.githubusercontent.com/20415092/42155888-e4a3fe4a-7de9-11e8-951e-e1dfba3c4d2c.png)

**Comment by FinnStutzenstein** [comment]
Same here: Do you want to do this, or shall I?

**Comment by jwinzer** [comment]
Please assign to yourself.

**Comment by FinnStutzenstein** [comment]
I cannot recreate this. Do you can?

**Comment by jwinzer** [comment]
This always happens to me.

**Comment by FinnStutzenstein** [comment]
This site.js is in OpenSlides. I cannot debug this, because this doesn't happen. Can you put before [this line](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/assignments/static/js/assignments/site.js#L703) these both statements:
```
console.log(assignmentpollId);
console.log(AssignmentPoll.get(assignmentpollId));
```
Maybe, the first one is undefined, so the second one, too. If yes, we need to investigate, why it's undefined.
